parameters:
#    jim_p0700.example.class: Jim\P0700Bundle\Example

services:
#    jim_p0700.example:
#        class: %jim_p0700.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    jim_p0700_user.registration.form.type:
        class: Jim\P0700Bundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: jim_p0700_user_registration }
